# Render Blueprint to provision three services: frontend (Next.js), backend (NestJS), and thumbnail (FastAPI)
# Docs: https://render.com/docs/blueprint-spec

services:
  - type: web
    name: youtube-grouth-ai-frontend
    rootDir: frontend
    env: node
    plan: free
    autoDeploy: true
    buildCommand: |
      npm ci
      npm run build
    startCommand: npm start
    envVars:
      # REQUIRED: Set these in Render Dashboard after first deploy
      - key: NEXTAUTH_URL
        sync: false
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NEXT_PUBLIC_API_URL
        value: https://youtube-grouth-ai-backend.onrender.com
      - key: BACKEND_URL
        value: https://youtube-grouth-ai-backend.onrender.com
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false

  - type: web
    name: youtube-grouth-ai-backend
    rootDir: backend
    env: node
    plan: free
    autoDeploy: true
    buildCommand: |
      npm ci
      npm run build
    startCommand: npm run start:prod
    healthCheckPath: /api/docs
    envVars:
      # CORS
      - key: ALLOWED_ORIGINS
        value: https://youtube-grouth-ai.onrender.com
      # Auth & Providers
      - key: JWT_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: THUMBNAIL_PROVIDER
        value: render
      - key: RENDER_THUMBNAIL_SERVICE_URL
        value: https://youtube-grouth-ai-thumbnail.onrender.com
      - key: RENDER_API_KEY
        sync: false
      # Backend URL (optional for internal callbacks)
      - key: BACKEND_URL
        value: https://youtube-grouth-ai-backend.onrender.com
      # Database / Supabase (provide your own values)
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: ADMIN_EMAILS
        sync: false

  - type: web
    name: youtube-grouth-ai-thumbnail
    rootDir: thumbnail-service
    env: python
    plan: free
    autoDeploy: true
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      # If you need an API key check in this service, add and validate it here
      - key: RENDER_API_KEY
        sync: false
