name: Deploy YouTube Growth AI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  NODE_VERSION: '18.x'
  PYTHON_VERSION: '3.11'

jobs:
  # Frontend Build & Deploy
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        if: ${{ secrets.VERCEL_TOKEN != '' && secrets.VERCEL_ORG_ID != '' && secrets.VERCEL_PROJECT_ID != '' }}

      - name: Setup Node.js
        if: ${{ secrets.VERCEL_TOKEN != '' && secrets.VERCEL_ORG_ID != '' && secrets.VERCEL_PROJECT_ID != '' }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        if: ${{ secrets.VERCEL_TOKEN != '' && secrets.VERCEL_ORG_ID != '' && secrets.VERCEL_PROJECT_ID != '' }}
        working-directory: ./frontend
        run: npm ci

      - name: Build
        if: ${{ secrets.VERCEL_TOKEN != '' && secrets.VERCEL_ORG_ID != '' && secrets.VERCEL_PROJECT_ID != '' }}
        working-directory: ./frontend
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
          NEXT_PUBLIC_ADSENSE_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_ADSENSE_CLIENT_ID }}
        run: npm run build

      - name: Deploy to Vercel
        if: ${{ secrets.VERCEL_TOKEN != '' && secrets.VERCEL_ORG_ID != '' && secrets.VERCEL_PROJECT_ID != '' }}
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./frontend
          vercel-args: '--prod'

  # Backend Build & Deploy
  deploy-backend:
    runs-on: ubuntu-latest
    env:
      RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
      RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
    steps:
      - uses: actions/checkout@v4
        if: ${{ env.RENDER_API_KEY != '' && env.RENDER_SERVICE_ID != '' }}

      - name: Setup Node.js
        if: ${{ env.RENDER_API_KEY != '' && env.RENDER_SERVICE_ID != '' }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies
        if: ${{ env.RENDER_API_KEY != '' && env.RENDER_SERVICE_ID != '' }}
        working-directory: ./backend
        run: npm ci

      - name: Build
        if: ${{ env.RENDER_API_KEY != '' && env.RENDER_SERVICE_ID != '' }}
        working-directory: ./backend
        run: npm run build

      - name: Deploy to Render
        if: ${{ env.RENDER_API_KEY != '' && env.RENDER_SERVICE_ID != '' }}
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          curl -X POST "https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys" \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Content-Type: application/json"

  # Thumbnail Service Deploy
  deploy-thumbnail-service:
    runs-on: ubuntu-latest
    env:
      RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
      RENDER_THUMBNAIL_SERVICE_ID: ${{ secrets.RENDER_THUMBNAIL_SERVICE_ID }}
    steps:
      - uses: actions/checkout@v4
        if: ${{ env.RENDER_API_KEY != '' && env.RENDER_THUMBNAIL_SERVICE_ID != '' }}

      - name: Setup Python
        if: ${{ env.RENDER_API_KEY != '' && env.RENDER_THUMBNAIL_SERVICE_ID != '' }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        if: ${{ env.RENDER_API_KEY != '' && env.RENDER_THUMBNAIL_SERVICE_ID != '' }}
        working-directory: ./thumbnail-service
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to Render
        if: ${{ env.RENDER_API_KEY != '' && env.RENDER_THUMBNAIL_SERVICE_ID != '' }}
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_THUMBNAIL_SERVICE_ID: ${{ secrets.RENDER_THUMBNAIL_SERVICE_ID }}
        run: |
          curl -X POST "https://api.render.com/v1/services/$RENDER_THUMBNAIL_SERVICE_ID/deploys" \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Content-Type: application/json"

  # Run Tests
  test:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Test Frontend
        working-directory: ./frontend
        run: |
          npm ci
          npm run lint

      - name: Test Backend
        working-directory: ./backend
        run: |
          npm ci
          npm run lint
          npm run test

      - name: Test Thumbnail Service
        working-directory: ./thumbnail-service
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
          # pytest tests/ (add when tests are created)
